name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "wasabi"
          heroku_email: "siddharth.polisiti@gmail.com"
          usedocker: true  // make sure to be true
          docker_build_args: |
            NODE_ENV
        env:
          NODE_ENV: production
          SECRET_KEY: 90f6c4d3-8e74-457d-b8d5-cec87d47903a
